### ISSUE TITLE
DecodeException while combining soundtrack after 7-1-2019 update

### ISSUE THREAD

**Issue by konyzulphurea** [villermen/runescape-cache-tools#63]
I have received an error like this, I try to use older method to find out the root cause.

E:\runescape-cache-tools-v3.0.4>rsct304 -c="C:\Users\konyzulphurea\Desktop\RSCD\data" -s
Villermen.RuneScapeCacheTools.Exceptions.DecodeException: Enum data does not contain a key type.
   at Villermen.RuneScapeCacheTools.Cache.Files.EnumFile.Decode(Byte[] data)
   at Villermen.RuneScapeCacheTools.Cache.Files.CacheFile.FromDataFile(BinaryFile dataFile)
   at Villermen.RuneScapeCacheTools.Cache.CacheBase.GetFile[T](Index index, Int32 fileId, Int32 entryId)
   at Villermen.RuneScapeCacheTools.Soundtrack.GetTrackNames(Boolean includeUnnamed)
   at Villermen.RuneScapeCacheTools.Soundtrack.Extract(Boolean overwriteExisting, Boolean lossless, Boolean includeUnnamed, String[] nameFilters)
   at Villermen.RuneScapeCacheTools.CLI.Program.CombineSoundtrack()
   at Villermen.RuneScapeCacheTools.CLI.Program.Main(String[] args)

E:\runescape-cache-tools-v3.0.4>

**Comment by villermen** [comment]
@konyzulphurea Thanks for reporting. I got the same error yesterday trying to update my local copy of the soundtrack. It's probably a logical error on my part or a change in Jagex's protocol. I'm going to look into it and hopefully have it fixed before this weekend.

**Comment by konyzulphurea** [comment]
That's so fast, by the way, I might try using older ways to take a look.

**Comment by villermen** [comment]
I think I fixed this issue over a year ago but haven't pushed a new release because the program wasn't in a fully working state yet. I hopefully fixed that now (but I'm a bit rusty). It worked for me. Can you check if it works for you with [v3.1.0](https://github.com/villermen/runescape-cache-tools/releases/tag/v3.1.0)? Please take note of the release message if you're going to be using it on an existing soundtrack directory.

Thanks in advance.

**Comment by konyzulphurea** [comment]
I take a look later.

Sjoerd Nuijten <notifications@github.com> 於 2019年1月11日 週五 04:43寫道：

**Comment by konyzulphurea** [comment]
It is bascially dealt. I'm testing if there are more issues.

**Comment by villermen** [comment]
Great. I'll check up on it soon™ to see if anything broke as well. If you do find anything feel free to create a new issue for it.
