### ISSUE TITLE
Download issues

### ISSUE THREAD

**Issue by LEETUMBRA** [villermen/runescape-cache-tools#78]
C:\Users\[REDACTED]\rsct-4.1.5>rsct audio --download -flac --unnamed
[01:57:21 INF] Obtained [REDACTED] soundtrack names and file IDs.
[01:58:28 FTL] File request for 255/40 timed out after 10 seconds.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Villermen.RuneScapeCacheTools.Cache.Downloader.TcpFileRequest.<WaitForCompletionAsync>d__24.MoveNext()

**Comment by villermen** [comment]
@LEETUMBRA Thanks for reporting this! I have not been able to reproduce this issue yet. It seems the tool hangs on obtaining the reference table of the music index (40) for you. Is this still the case? It might've been a temporary download server outage.

```
$ mono rsct.exe audio --download --flac --unnamed
[07:49:57 INF] Obtained 1520 soundtrack names and file IDs.
[07:50:09 INF] Combined "64".
[07:50:10 INF] Combined "Taverley Lament".
[07:50:10 INF] Combined "71".
```
