### ISSUE TITLE
[Bug] Unable to download

### ISSUE THREAD

**Issue by pxssy** [villermen/runescape-cache-tools#86]
```
rsct audio --download --flac --unnamed --verbose
[DBG] Attempting to connect to TCP content server with version 926.1...
[DBG] Successfully connected to content server with version 926.1.
[DBG] TCP request processor failed.
[FTL] The requested amount of bytes (128) could not be read. Only 0 bytes were available.
   at Villermen.RuneScapeCacheTools.Utility.BinaryStreamExtensions.ReadBytesExactly(BinaryReader reader, Int32 count)
   at Villermen.RuneScapeCacheTools.Cache.Downloader.TcpFileDownloader.Connect()
   at Villermen.RuneScapeCacheTools.Cache.Downloader.TcpFileDownloader.ProcessRequests()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Villermen.RuneScapeCacheTools.Cache.Downloader.TcpFileRequest.<WaitForCompletionAsync>d__24.MoveNext()
```

I'm not sure what's happening nor what did I do wrong. I've used your tool before and it has worked well.

**Comment by villermen** [comment]
@pxssy Thanks for reporting. I'm seeing the same thing and am hoping to fix this before the weekend!

**Comment by villermen** [comment]
d9673421d1458d4f2c79c6c0208bd622dcc0f876 should've fixed the issue. I'm not sure if this is a temporary change on Jagex's end, but it's a welcome one. If it breaks next update the previous version might start working again.
